# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Checking for unchecked errors
    - govet         # Examines Go source code
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Checks for unused code
    - misspell      # Finds commonly misspelled words

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  revive:
    severity: warning
    enable-all-rules: false
    rules:
      - name: package-comments
        severity: warning
      - name: errcheck
        severity: warning

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
        - revive

    # Ignore long lines in generated files
    - path: docs/docs.go
      linters:
        - lll

    # Exclude revive checks for specific patterns
    - linters:
        - revive
      text: "(stutters|exported.*should have comment|unused-parameter)"
      path: "(repository\\.go|handler\\.go|.*_gorm\\.go|adapter\\.go)"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
