version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fits_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fits_db
      POSTGRES_USER: fits_user
      POSTGRES_PASSWORD: fits_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fits_user -d fits_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: fits_network
