[server]
port = 8080
host = "0.0.0.0"
read_timeout = "30s"
write_timeout = "30s"

[secrets]
metrics_secret = "i-forgot-my-token="
registration_secret = "i-forgot-my-token="
deletion_secret = "i-forgot-my-token="
update_secret = "i-forgot-my-token="

[storage]
upload_dir = "./uploads"
max_file_size = 104857600

[logging]
level = "info"
format = "json"
