[server]
port = 8080
host = "0.0.0.0"
read_timeout = "30s"
write_timeout = "30s"
# Comma-separated CORS origins. Use "*" for all (dev only), or specify: "http://localhost:3000,https://example.com"
allowed_origins = "*"
# Rate limit: max requests per minute per IP. 0 = unlimited (not recommended for production)
rate_limit = 100

# TLS/HTTPS Configuration (recommended for production)
tls_enabled = false
tls_cert_file = "./certs/server.crt"
tls_key_file = "./certs/server.key"
tls_auto_redirect = false  # Auto-redirect HTTP to HTTPS (requires running on both ports)

[secrets]
metrics_secret = "i-forgot-my-token="
registration_secret = "i-forgot-my-token="
deletion_secret = "i-forgot-my-token="
update_secret = "i-forgot-my-token="

[storage]
upload_dir = "./uploads"
max_file_size = 104857600

[logging]
level = "info"
format = "json"

[database]
host = "localhost"
port = 5432
user = "fits_user"
password = "fits_password"
database = "fits_db"
ssl_mode = "disable"
max_conns = 25
min_conns = 5

[jwt]
# SECURITY: Must be at least 32 characters for HS256. Change in production!
# Generate with: openssl rand -base64 32
secret = "CHANGE-THIS-SECRET-KEY-IN-PRODUCTION-USE-OPENSSL-RAND-BASE64-32"
access_token_expiry = "1h"
refresh_token_expiry = "720h"  # 30 days
invitation_expiry = "168h"      # 7 days
admin_key_path = "./configs/keys/admin.key"
admin_pub_key_path = "./configs/keys/admin.pub"
